// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module e2e_system_dataflow_parent_loop_proc (
        input_data_address0,
        input_data_ce0,
        input_data_d0,
        input_data_q0,
        input_data_we0,
        input_data_address1,
        input_data_ce1,
        input_data_d1,
        input_data_q1,
        input_data_we1,
        correlators_output_V_address0,
        correlators_output_V_ce0,
        correlators_output_V_d0,
        correlators_output_V_q0,
        correlators_output_V_we0,
        correlators_output_V_address1,
        correlators_output_V_ce1,
        correlators_output_V_d1,
        correlators_output_V_q1,
        correlators_output_V_we1,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


output  [8:0] input_data_address0;
output   input_data_ce0;
output  [31:0] input_data_d0;
input  [31:0] input_data_q0;
output   input_data_we0;
output  [8:0] input_data_address1;
output   input_data_ce1;
output  [31:0] input_data_d1;
input  [31:0] input_data_q1;
output   input_data_we1;
output  [5:0] correlators_output_V_address0;
output   correlators_output_V_ce0;
output  [31:0] correlators_output_V_d0;
input  [31:0] correlators_output_V_q0;
output   correlators_output_V_we0;
output  [5:0] correlators_output_V_address1;
output   correlators_output_V_ce1;
output  [31:0] correlators_output_V_d1;
input  [31:0] correlators_output_V_q1;
output   correlators_output_V_we1;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

reg ap_done;
reg ap_ready;
reg ap_idle;

wire   [8:0] dataflow_in_loop_PROCESSOR_U0_input_data_address0;
wire    dataflow_in_loop_PROCESSOR_U0_input_data_ce0;
wire   [31:0] dataflow_in_loop_PROCESSOR_U0_input_data_d0;
wire    dataflow_in_loop_PROCESSOR_U0_input_data_we0;
wire   [8:0] dataflow_in_loop_PROCESSOR_U0_input_data_address1;
wire    dataflow_in_loop_PROCESSOR_U0_input_data_ce1;
wire   [31:0] dataflow_in_loop_PROCESSOR_U0_input_data_d1;
wire    dataflow_in_loop_PROCESSOR_U0_input_data_we1;
wire   [5:0] dataflow_in_loop_PROCESSOR_U0_correlators_output_V_address0;
wire    dataflow_in_loop_PROCESSOR_U0_correlators_output_V_ce0;
wire   [31:0] dataflow_in_loop_PROCESSOR_U0_correlators_output_V_d0;
wire    dataflow_in_loop_PROCESSOR_U0_correlators_output_V_we0;
wire   [5:0] dataflow_in_loop_PROCESSOR_U0_correlators_output_V_address1;
wire    dataflow_in_loop_PROCESSOR_U0_correlators_output_V_ce1;
wire   [31:0] dataflow_in_loop_PROCESSOR_U0_correlators_output_V_d1;
wire    dataflow_in_loop_PROCESSOR_U0_correlators_output_V_we1;
wire    dataflow_in_loop_PROCESSOR_U0_ap_start;
wire    dataflow_in_loop_PROCESSOR_U0_ap_done;
wire    dataflow_in_loop_PROCESSOR_U0_ap_ready;
wire    dataflow_in_loop_PROCESSOR_U0_ap_idle;
reg    dataflow_in_loop_PROCESSOR_U0_ap_continue;
wire    ap_sync_continue;
wire    ap_sync_done;
wire    ap_sync_ready;
reg   [7:0] loop_dataflow_input_count;
reg   [7:0] loop_dataflow_output_count;
wire   [7:0] bound_minus_1;
wire    dataflow_in_loop_PROCESSOR_U0_start_full_n;
wire    dataflow_in_loop_PROCESSOR_U0_start_write;

// power-on initialization
initial begin
#0 loop_dataflow_input_count = 8'd0;
#0 loop_dataflow_output_count = 8'd0;
end

e2e_system_dataflow_in_loop_PROCESSOR dataflow_in_loop_PROCESSOR_U0(
    .input_data_address0(dataflow_in_loop_PROCESSOR_U0_input_data_address0),
    .input_data_ce0(dataflow_in_loop_PROCESSOR_U0_input_data_ce0),
    .input_data_d0(dataflow_in_loop_PROCESSOR_U0_input_data_d0),
    .input_data_q0(input_data_q0),
    .input_data_we0(dataflow_in_loop_PROCESSOR_U0_input_data_we0),
    .input_data_address1(dataflow_in_loop_PROCESSOR_U0_input_data_address1),
    .input_data_ce1(dataflow_in_loop_PROCESSOR_U0_input_data_ce1),
    .input_data_d1(dataflow_in_loop_PROCESSOR_U0_input_data_d1),
    .input_data_q1(input_data_q1),
    .input_data_we1(dataflow_in_loop_PROCESSOR_U0_input_data_we1),
    .i_3(loop_dataflow_input_count),
    .correlators_output_V_address0(dataflow_in_loop_PROCESSOR_U0_correlators_output_V_address0),
    .correlators_output_V_ce0(dataflow_in_loop_PROCESSOR_U0_correlators_output_V_ce0),
    .correlators_output_V_d0(dataflow_in_loop_PROCESSOR_U0_correlators_output_V_d0),
    .correlators_output_V_q0(32'd0),
    .correlators_output_V_we0(dataflow_in_loop_PROCESSOR_U0_correlators_output_V_we0),
    .correlators_output_V_address1(dataflow_in_loop_PROCESSOR_U0_correlators_output_V_address1),
    .correlators_output_V_ce1(dataflow_in_loop_PROCESSOR_U0_correlators_output_V_ce1),
    .correlators_output_V_d1(dataflow_in_loop_PROCESSOR_U0_correlators_output_V_d1),
    .correlators_output_V_q1(correlators_output_V_q1),
    .correlators_output_V_we1(dataflow_in_loop_PROCESSOR_U0_correlators_output_V_we1),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .i_3_ap_vld(1'b0),
    .ap_start(dataflow_in_loop_PROCESSOR_U0_ap_start),
    .ap_done(dataflow_in_loop_PROCESSOR_U0_ap_done),
    .ap_ready(dataflow_in_loop_PROCESSOR_U0_ap_ready),
    .ap_idle(dataflow_in_loop_PROCESSOR_U0_ap_idle),
    .ap_continue(dataflow_in_loop_PROCESSOR_U0_ap_continue)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_input_count <= 8'd0;
    end else begin
        if ((~(loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_PROCESSOR_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= (loop_dataflow_input_count + 8'd1);
        end else if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_PROCESSOR_U0_ap_ready == 1'b1))) begin
            loop_dataflow_input_count <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        loop_dataflow_output_count <= 8'd0;
    end else begin
        if ((~(loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_PROCESSOR_U0_ap_continue == 1'b1) & (dataflow_in_loop_PROCESSOR_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= (loop_dataflow_output_count + 8'd1);
        end else if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_PROCESSOR_U0_ap_continue == 1'b1) & (dataflow_in_loop_PROCESSOR_U0_ap_done == 1'b1))) begin
            loop_dataflow_output_count <= 8'd0;
        end
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == bound_minus_1) & (dataflow_in_loop_PROCESSOR_U0_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_output_count == 8'd0) & (ap_start == 1'b0) & (dataflow_in_loop_PROCESSOR_U0_ap_idle == 1'b1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((loop_dataflow_input_count == bound_minus_1) & (ap_start == 1'b1) & (dataflow_in_loop_PROCESSOR_U0_ap_ready == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~(loop_dataflow_output_count == bound_minus_1) | (ap_continue == 1'b1))) begin
        dataflow_in_loop_PROCESSOR_U0_ap_continue = 1'b1;
    end else begin
        dataflow_in_loop_PROCESSOR_U0_ap_continue = 1'b0;
    end
end

assign ap_sync_continue = ap_continue;

assign ap_sync_done = dataflow_in_loop_PROCESSOR_U0_ap_done;

assign ap_sync_ready = dataflow_in_loop_PROCESSOR_U0_ap_ready;

assign bound_minus_1 = (8'd170 - 8'd1);

assign correlators_output_V_address0 = dataflow_in_loop_PROCESSOR_U0_correlators_output_V_address0;

assign correlators_output_V_address1 = dataflow_in_loop_PROCESSOR_U0_correlators_output_V_address1;

assign correlators_output_V_ce0 = dataflow_in_loop_PROCESSOR_U0_correlators_output_V_ce0;

assign correlators_output_V_ce1 = dataflow_in_loop_PROCESSOR_U0_correlators_output_V_ce1;

assign correlators_output_V_d0 = dataflow_in_loop_PROCESSOR_U0_correlators_output_V_d0;

assign correlators_output_V_d1 = 32'd0;

assign correlators_output_V_we0 = dataflow_in_loop_PROCESSOR_U0_correlators_output_V_we0;

assign correlators_output_V_we1 = 1'b0;

assign dataflow_in_loop_PROCESSOR_U0_ap_start = ap_start;

assign dataflow_in_loop_PROCESSOR_U0_start_full_n = 1'b1;

assign dataflow_in_loop_PROCESSOR_U0_start_write = 1'b0;

assign input_data_address0 = dataflow_in_loop_PROCESSOR_U0_input_data_address0;

assign input_data_address1 = dataflow_in_loop_PROCESSOR_U0_input_data_address1;

assign input_data_ce0 = dataflow_in_loop_PROCESSOR_U0_input_data_ce0;

assign input_data_ce1 = dataflow_in_loop_PROCESSOR_U0_input_data_ce1;

assign input_data_d0 = 32'd0;

assign input_data_d1 = 32'd0;

assign input_data_we0 = 1'b0;

assign input_data_we1 = 1'b0;

endmodule //e2e_system_dataflow_parent_loop_proc
